version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR to fetch image from secondary account...
      - $(aws ecr get-login --registry-ids $CROSS_ACCOUNT_ID --no-include-email --region $CROSS_ACOUNT_REGION)
      - docker pull $CROSS_ACCOUNT_ID.dkr.ecr.$CROSS_ACOUNT_REGION.amazonaws.com/$CROSS_ACCOUNT_REPO:$CROSS_ACCOUNT_TAG
      - docker image ls
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo pushing the image into our ecr repository...          
      - $(aws ecr get-login  --no-include-email --region $AWS_DEFAULT_REGION)
      - docker tag $CROSS_ACCOUNT_ID.dkr.ecr.$CROSS_ACOUNT_REGION.amazonaws.com/$CROSS_ACCOUNT_REPO:$CROSS_ACCOUNT_TAG  $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker image ls
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
